# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
